"""Create the 21 missing knowledge_seed entries (1-7, 15-21, 22-28) for the coach.
Content distilled from KB_EVALUATION.md and AM_KB_SATURATION.md. No em dashes."""
import os
SEED = "/home/flask/tradewave_realtime/knowledge_seed"
SRC = 'Anne-Marie Baiynd "Blueprint Open" daily videos (2026)'

E = [
("yt_a_01_grade_the_trend","Grade the trend first","method",
 "Before looking for any entry, grade the trend. Read the alignment and slope of the 20, 50, and 200 SMAs (mainly on the 30-minute, dropping to the hourly or 4-hour when the 30-minute is too noisy). Positive trend (averages rising and stacked bullishly): dips are buys. Negative trend (averages falling): bounces are sell zones. Sideways (the 50 flat, pivots clustered close together): trade the edges, not the middle, and wait for a breakout. Pick whichever timeframe shows the formation most cleanly rather than defaulting to a fixed one. This grade sets your bias for the whole session before a single level is considered."),
("yt_a_02_200_sma_mean_reversion","The 200 SMA as a mean-reversion magnet and multi-timeframe filter","method",
 "The 200 SMA is the primary long-term filter and a mean-reversion target, not just a binary gate. When price drifts far above the rising 20, 50, and 200, demand is exhausting and price tends to rotate back into the averages: that compression back toward them is the dip-buy setup, and the averages tightening is the signal it is near. Read the 200 across timeframes (30-minute, hourly, 4-hour, daily): in an uptrend, bounces into a rising 200 are buy zones, and a clean break below it on higher frames flips it to a short signal. The 50 is secondary structure, the 20 is the near-term momentum read. The 200 is the most statistically significant line on the chart."),
("yt_a_03_ma_squeeze","The moving-average squeeze precedes big moves","method",
 "When the 50 and 200 SMAs converge (especially when one slopes up and the other down), a large move is building. Price ping-pongs inside the tightening range until it breaks free. The squeeze tells you a move is imminent, not its direction, so prepare for expansion and let the break confirm direction rather than guessing. Treat converging averages or a wedge the same way: pressure building toward a release. Do not pick a side early. Mark the range and trade the resolution."),
("yt_a_04_fibonacci_guardrail","Fibonacci as a structural guardrail","method",
 "Draw Fibonacci both peak-to-base and base-to-peak, anchored to a meaningful candle (the dominant or highest-volume bar, the opening candle, or a major swing), across the 30-minute, hourly, and daily. Use retracements to mark where pullbacks should floor (the 50 percent midpoint is the key bounce zone, 25 and 75 percent are secondary) and extensions to project upside targets beyond the moving averages. Fibonacci levels are guardrails and target confirmation used alongside moving averages and structural levels, never in isolation. Where a Fib level lines up with a pivot or an average, that confluence strengthens it."),
("yt_a_05_gamma_walls","Gamma walls, the gamma flip, and dealer hedging","method",
 "Read options-derived levels as structure. Call walls sit above price and act as resistance, put walls sit below and act as support, and the gamma flip is where the market switches from positive to negative gamma and tends to reject. These walls move as dealer inventory shifts, so track how they migrate to read flow intent. Zero-DTE walls are short-term intraday references that rotate quickly and should carry less weight than larger-expiry walls. Mechanics matter: if price breaks a call wall and does not immediately fade, dealers are forced to hedge by buying, which extends the move into the next supply zone. This is part of why her dip-buys work: dealers are defending gamma."),
("yt_a_06_anchored_vwap_value_area","Anchored VWAP, value area, and volume profile","method",
 "Anchor VWAP to a specific high-volume event (the session open, the 9:30 candle, a prior-day open, a dominant volume bar) rather than using a generic VWAP: the precise anchor gives a sharper mean-reversion target and a cleaner read of shallow versus deep dips. A rising VWAP is bullish, a flat or falling VWAP is bearish (sell bounces off it). From market profile, the value-area high and low frame where most volume traded: price rotates back into the value area, and losing the value-area low signals a deeper pullback. Unfilled gaps tend to fill, which can serve as a longer-term target."),
("yt_a_07_momentum_divergence","Momentum divergence as a trend-fatigue flag","method",
 "Watch momentum as a separate signal from price. When price makes a higher high but momentum makes a lower high (or a lower low in price with a higher low in momentum), the move is fatiguing and a reversal at the next structural level becomes likely. The slope of the momentum line shows how committed buyers or sellers are. A common combination: rising price and a rising 200 SMA but falling momentum equals a shallow drift back into support, not a reversal. Use divergence to avoid entering into deteriorating conditions, not as a standalone trigger."),

("yt_c_15_order_flow","Order-flow primacy, the root cause behind price","method",
 "The candle and the level are effects, not causes. Order flow is the answer to which way. Price goes where the volume is. Read levels as places where flow is likely to react, but never trust a level without the flow confirming it. This mental layer sits underneath every other entry: dealers, retail, options traders, and institutions all move price through their orders. Watch the footprints, where volume clusters and where participants bunch up, and you will see where price gravitates. Skip the level if the flow is not behind it."),
("yt_c_16_wall_oscillation","Wall-bounded oscillation and intraday wall migration","method",
 "Dealers trap price between the put wall and the call wall and defend both. Price ping-pongs inside until it breaks a wall, then accelerates as dealers hedge. Critically, the walls themselves move intraday (zero-DTE walls especially) as dealers re-hedge delta. Re-read the walls during the session: do not treat the morning map as fixed. A wall that was here at 9:30 may have jumped by 11:00. The oscillation inside the walls is mechanical, the breakout is the turn. Mark the walls fresh through the day."),
("yt_c_17_confluence","Confluence and vertical-stack compression","method",
 "When pivot, VWAP, anchored VWAP, and the 50 SMA cluster at the same price, that zone is ultra-sticky and high-probability. When the 200, 50, and VWAP stack vertically and landlocked, the market is coiled and a breakaway is near in the direction of the prior trend. Confluence raises conviction. A vertical stack is a timing tell: something is about to move. The more levels that agree on one price, the more certain the reaction. Lean harder on a zone where all roads lead to one price."),
("yt_c_18_slope_flat_ma","Slope and the flat-MA chop filter","method",
 "The direction of a moving average matters as much as price relative to it. A flat 50, flat 200, or flat VWAP signals chop ahead: do not expect clean continuation. Upslope plus price above equals strong, flat VWAP under a trend means consolidation and a retest are imminent. Use slope to decide whether to trade trend or stand aside. If the average is climbing, take the trend. If it is flat or rolling, step back and wait for the compression to finish. Slope tells you the character of the next move before it happens."),
("yt_c_19_volume_profile","Volume-profile structure, POC, bimodal nodes, and thin pockets","method",
 "Point of control is the market's hub and a magnet. Bimodal or multimodal profiles (two or three distinct volume pockets) signal extended chop and mark precise re-test and bounce zones. Thin volume pockets get run through fast once momentum engages, so they forecast the next leg's target. Value-area width reads as inventory: wide equals distribution, narrow equals accumulation. Read the profile to see where the market actually traded, where buyers and sellers met most, and where they will fight again. The POC is not resistance, it is gravity."),
("yt_c_20_session_anchors","Session time-anchors, the structural reference frames","method",
 "Specific candles are structural reference frames. The 4am London candle sets the daily go or no-go (a close above the prior pivot favors a trend day). The Globex open is front-line support and resistance. The market-on-open and market-on-close candles anchor the day and mark where passive buyers and sellers punch in. The midnight candle is a threshold that often gets revisited intraday, useful as a reference zone. Mark these candles before the open: they are not noise, they are the session's skeleton."),
("yt_c_21_cumulative_delta","Cumulative delta and pre-market positioning","method",
 "Cumulative delta flipping negative pre-market reveals seller dominance before the open, which tells you whether to fade or buy the first move. Read delta as a confirmation layer on top of overnight inventory and the wall map. Rising cumulative delta with rising price is real buying, while price up on flat or falling delta warns the move is hollow and likely to reverse. Use delta to confirm, not to lead."),

("yt_d_22_max_pain","Max pain as a magnet in compressed markets","method",
 "In sideways, gamma-pinned markets, options max pain acts as a gravitational attractor distinct from ordinary support and resistance. On a Friday expiration expect up to three pulls toward it (before the open, at the open, and into the close). Use it as the center of gravity, not as a tradeable edge by itself. In a trending market it matters far less. When the market is pinned and quiet, respect the pull."),
("yt_d_23_futures_curve","The futures curve, backwardation, contango, and contract rolls","method",
 "The forward curve is a structural driver independent of spot. Backwardation lifts prices through roll cost, contango pressures them. Contract rolls create visible volume cliffs, jagged formations, and gap-fills that must complete before continuation. Treat roll days as mechanical, not directional, and let the gap-fill finish before you read the next trend. The curve is a slow tailwind or headwind sitting underneath the chart."),
("yt_d_24_if_and_then","The if-and-then conditional entry rule","method",
 "Never anticipate, confirm. A valid entry needs two parts: the breakout AND a successful pullback that holds the broken level. If both happen, then you trade. If the level cannot be recaptured, you stay out. The corollary: a failed breakdown that recaptures the level confirms a reversal up, while a bounce that cannot recapture confirms continuation down. Break and hold, then act. This is her most repeated risk-structuring rule after the core: it keeps you out of the fake-out and in the real move."),
("yt_d_25_reflexive_bounces","Reflexive bounces in hedged or falling markets","psychology",
 "In a heavily hedged market, bounces after hard selling are automatic and mechanical, not trend reversals. Do not confuse a reflex bounce for a bottom, and do not add shorts into the aggressive fade. The structure of the bounce tells you the next move: look above and go means continuation, look below and fail means sell the bounce. Avoid the falling knife and wait for the reflex to confirm. Respect that the bounce is coming, then read whether it holds."),
("yt_d_26_crosscurrent","Crosscurrents, when the timeframes disagree","psychology",
 "When timeframes disagree on trend, it is a battleground that demands tighter risk and smaller size, or standing aside. Trend is up, momentum is down is the canonical crosscurrent. Name the disagreement out loud instead of forcing a side. A crosscurrent is not a reason to trade harder, it is a reason to trade smaller or wait. The cleanest setups come when the timeframes line up."),
("yt_d_27_seasonality","Seasonality and calendar flow effects","faq",
 "Repeatable calendar rhythms shape the odds without predicting news: the Santa rally and post-Christmas drift, January fear, VIX expiring after the indices (which can flip flow afterward), buyback windows opening, and month-end plus quad-witching and OPEX hedging. Use these to game probabilities, but manage daily risk inside them. Seasonality leans the odds, it is never a license for loose stops or a reason to override what the chart is actually doing."),
("yt_d_28_wall_inversions","Confused option positioning and wall inversions","method",
 "When the call wall sits below the put wall, or zero-DTE and month-end walls point in opposite directions, option traders are structurally offside and will be forced to re-hedge. This positioning tell reliably precedes outsized swings as one side gets flushed out. When the walls are in sync, expect consensus and a calmer range. When they are inverted, expect a squeeze. Read the walls against each other, not just against price."),
]

n=0
for slug,title,cat,body in E:
    p=os.path.join(SEED,f"{slug}.md")
    open(p,"w",encoding="utf-8").write(f"---\ntitle: {title}\ncategory: {cat}\nsource: {SRC}\n---\n{body}\n")
    assert "—" not in open(p,encoding="utf-8").read(), f"em dash in {slug}"
    n+=1
print(f"wrote {n} entry files")
